apiVersion: apps/v1
kind: Deployment
metadata:
  name: sit727-gke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sit727-felix
  template:
    metadata:
      labels:
        app: sit727-felix
    spec:
      containers:
      - name: sit727-felix-app
        # Replace $LOCATION with your Artifact Registry location (e.g., us-west1).
        # Replace $GCLOUD_PROJECT with your project ID.
        image: australia-southeast1-docker.pkg.dev/sit727-24t1-nguyen-0415166/sit727-felix-artifact-reg/sit727-felix-gke:latest
        # This app listens on port 8080 for web traffic by default.
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            value: "8080"
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"
          limits:
            memory: "1Gi"
            cpu: "500m"
            ephemeral-storage: "1Gi"